
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src


COPY ["Sudoku.API/Sudoku.API.csproj", "Sudoku.API/"]
COPY ["Sudoku.Core/Sudoku.Core.csproj", "Sudoku.Core/"]
COPY ["Sudoku.Infrastructure/Sudoku.Infrastructure.csproj", "Sudoku.Infrastructure/"]


RUN dotnet restore "Sudoku.API/Sudoku.API.csproj"

COPY . .

WORKDIR "/src/Sudoku.API"
RUN dotnet publish "Sudoku.API.csproj" -c Release -o /app/out

FROM mcr.microsoft.com/dotnet/aspnet:10.0
WORKDIR /app
COPY --from=build /app/out .

ENV ASPNETCORE_URLS=http://+:80
EXPOSE 80

ENTRYPOINT ["dotnet", "Sudoku.API.dll"]